'use strict';

// tests for <%= functionName %>
// Generated by serverless-tdd-plugin

const TddPlugin = require('serverless-tdd-plugin');
const tddPlugin = new TddPlugin();
const expect = tddPlugin.initRunner({testFramework: 'mocha'}).getChai().expect;
let wrapped = tddPlugin.getWrapper('<%= functionName %>', '/<%= functionPath %>', '<%= handlerName %>');

describe('<%= functionName %>', () => {
  before((done) => {
    done();
  });

  it('implement tests here', () => {
    return wrapped.run({}).then((response) => {
      expect(response).to.not.be.empty;
    });
  });
});
